AppBundle\Entity\Alert:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        min:
            type: float
        max:
            type: float
    lifecycleCallbacks: {  }
